<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_button-inner-sia-4e7-5cc</name>
   <tag></tag>
   <elementGuidId>83a3ccd3-e661-4ebc-92c0-3c5ae8f077ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.button-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' button-inner ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb63d3d1-b06b-48af-a46b-46e60040505e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-inner</value>
      <webElementGuid>21a757ce-46fd-4dad-b4c9-a8da41c735b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4375f762cd60c95935b43dd5a378ce74</value>
      <webElementGuid>765075af-9652-47bb-90fc-41d8193b3f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' button-inner ')]</value>
      <webElementGuid>3a443b84-2901-46fd-a184-339e1edcb1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SkillHub/Asesment-Diri/Page_SIAPkerja  Kementerian Ketenagakerjaan_18fb92/ion-button_Lakukan Asesmen-donesia-4e7</value>
      <webElementGuid>fb47eda1-bb35-4224-9855-b8222b124582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>86e19a11-5828-4c6a-9950-e9a5d797e6d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' button-inner ')]</value>
      <webElementGuid>bbde57a7-cb66-4f84-a1f8-3828b5f9bd92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
