<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Verifikasi</name>
   <tag></tag>
   <elementGuidId>13db3424-7c63-4a92-92a0-3c679928df1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.text-xl.font-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='naco']/div/div/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>1b4bda0a-73cc-4a6a-a6f5-8cba5eb823c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xl font-bold</value>
      <webElementGuid>d01d0b74-0d47-42b5-b4bf-4e167aee10a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifikasi</value>
      <webElementGuid>9ff567a3-3933-466a-b39a-66fd5c26a235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;naco&quot;)/div[@class=&quot;pt-28 sm:pt-32&quot;]/div[@class=&quot;box auth-form relative&quot;]/div[@class=&quot;p-10&quot;]/div[@class=&quot;mb-10 text-center&quot;]/h4[@class=&quot;text-xl font-bold&quot;]</value>
      <webElementGuid>c002bf49-fc1b-4788-8b6b-0201e321e1cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='naco']/div/div/div/div/h4</value>
      <webElementGuid>c39ac8b4-e63c-4297-9924-2b6e33e9911f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verifikasi']/parent::*</value>
      <webElementGuid>7a9eb243-822d-4592-a4f5-4b11e03e5473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>1b5aa574-5e04-4f1e-9498-1cdef66ad194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Verifikasi' or . = 'Verifikasi')]</value>
      <webElementGuid>6d5eafe8-fadf-4023-a585-2c6718288e36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
