<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_palmerah</name>
   <tag></tag>
   <elementGuidId>fce06326-3421-4b43-b710-d957bd8f98aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-modal[@id='ion-overlay-3']/div/ion-content/ion-list/ion-item[5]/ion-label/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>45368209-3254-41da-bf14-b5e414c76b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base capitalize</value>
      <webElementGuid>f53a30f9-1b3b-4b32-8c89-26ae653864a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>palmerah</value>
      <webElementGuid>fd070b08-6521-4a2c-92e5-e009b8401a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-3&quot;)/div[@class=&quot;ion-delegate-host ion-page&quot;]/ion-content[@class=&quot;ios content-ltr hydrated&quot;]/ion-list[@class=&quot;ios list-ios hydrated&quot;]/ion-item[@class=&quot;item ios item-lines-default in-list ion-activatable ion-focusable hydrated item-label&quot;]/ion-label[@class=&quot;py-1 sc-ion-label-ios-h ios sc-ion-label-ios-s hydrated&quot;]/h4[@class=&quot;text-base capitalize&quot;]</value>
      <webElementGuid>c7d6e387-3b84-44c4-97c9-d3ac3e506e10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-modal[@id='ion-overlay-3']/div/ion-content/ion-list/ion-item[5]/ion-label/h4</value>
      <webElementGuid>b4b38553-a2b5-4499-a780-745247743a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kota bambu utara'])[1]/following::h4[1]</value>
      <webElementGuid>9447ef17-e9a5-4dba-8efd-c832f8c141a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kota bambu selatan'])[1]/following::h4[2]</value>
      <webElementGuid>7bc8e6e9-dae2-422c-8fde-7bef4444fa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slipi'])[1]/preceding::h4[1]</value>
      <webElementGuid>436fbc08-fe43-4293-8b18-6f8a038834d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='palmerah']/parent::*</value>
      <webElementGuid>66a921ea-2907-4894-afbb-c05a128f2308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-item[5]/ion-label/h4</value>
      <webElementGuid>745b6524-3b62-4a78-995e-fe2ef8a47560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'palmerah' or . = 'palmerah')]</value>
      <webElementGuid>61ebc903-bdb5-4c9e-8dbc-8a7640155f9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
