<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_inner-scroll scroll-y-sia-5eb-38a</name>
   <tag></tag>
   <elementGuidId>cb5a800e-662b-472e-885d-d5cf5e797637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.inner-scroll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' inner-scroll ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>599531e0-393b-4400-b2be-62bbf656bd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inner-scroll scroll-y</value>
      <webElementGuid>0735c716-5f25-4736-83d5-7444eeb4f69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>scroll</value>
      <webElementGuid>db5b628f-3d92-4588-89d1-a8b10c044d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f7467767888c6ad157c7fca8a59f0a83</value>
      <webElementGuid>04ace410-aaaa-415e-b3fa-5a747174dfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' inner-scroll ')]</value>
      <webElementGuid>91a0d5fb-0bab-493a-b61f-af00097bf935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAPKerja/Complete-Profile/Page_SIAPkerja  Kementerian Ketenagakerjaan_18fb92/ion-content_Selamat datang,RismawatiSIAPkerja-ID-donesia-5eb</value>
      <webElementGuid>c8935974-ab00-46af-bb56-bd0647d549d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36bedb58-9372-42cd-8739-7d31484f7f63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' inner-scroll ')]</value>
      <webElementGuid>fea5a664-d223-4513-abdd-af9091c62248</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
