<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_dki jakarta</name>
   <tag></tag>
   <elementGuidId>036f6bba-1749-4e23-91ef-70e614615d1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>d99186fe-546d-4c69-a326-23f7903893b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base capitalize</value>
      <webElementGuid>f4fcf276-be5b-433f-9b26-7a4293c13480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dki jakarta</value>
      <webElementGuid>2f4bfdc7-538b-4c51-b943-f2979b1b5d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1da9d7d7979802766bb66a73b3f3d49f</value>
      <webElementGuid>321ad98e-70a0-4f71-b7eb-61909e1a19df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>3cab8156-4646-49da-8c3d-8789fcf9d384</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>88f949b2-1f84-4f51-a0a8-a2734d8bb6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'dki jakarta' or . = 'dki jakarta')]</value>
      <webElementGuid>007f4539-b193-4d85-a7b9-f16fab072eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
