<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_developer</name>
   <tag></tag>
   <elementGuidId>6cbe3447-1f05-4adf-a337-77f300abdc73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[_ngcontent-ng-c1825902672=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@_ngcontent-ng-c1825902672 = '']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8bda5d3e-c006-44bd-81ce-ad9ea2b16c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-bold</value>
      <webElementGuid>cec6109e-5178-4083-97ae-c2786d185944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>developer</value>
      <webElementGuid>676dde36-1336-4bd5-aca4-72c041d1ed61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e4c64654e4819267e5c82c1aae638fb0</value>
      <webElementGuid>63761dca-f81b-43a5-b029-aee49983dbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@_ngcontent-ng-c1825902672 = '']</value>
      <webElementGuid>e2e83898-d75d-465f-8eab-22e0ae373f65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@_ngcontent-ng-c1825902672 = '']</value>
      <webElementGuid>fa72240a-8443-4bf7-a91c-b8740c439cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'developer' or . = 'developer')]</value>
      <webElementGuid>827f2b0f-2900-4569-9c57-ffdedafbb514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
