<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-checkbox_ion-cb-3-lbl-donesia-e33</name>
   <tag></tag>
   <elementGuidId>e72af5b7-b5fa-41a3-aecc-c6313ef6a432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;ion-cb-3-lbl&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'ion-cb-3-lbl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-checkbox</value>
      <webElementGuid>e9f10d92-775a-4b96-8c3c-8ed124638bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>slot</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>69a295a1-00b1-42a6-a74c-cb78c2ba539e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>md</value>
      <webElementGuid>785d0cc2-a07d-4461-9d30-e6cff0963624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isSeekingDomesticJobs</value>
      <webElementGuid>81160b92-d1c5-4dd0-b74f-6c553866c9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelplacement</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>f33786cd-78c9-492d-ab89-13496ef10bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>justify</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>bc44e2f7-b936-430f-850b-c3ff90bfd450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid md in-item interactive checkbox-justify-start checkbox-label-placement-end hydrated ion-untouched ion-pristine ion-valid</value>
      <webElementGuid>bc23c792-b28b-42bf-9b91-5296ac6d75d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fd11ce16-bfc4-4a35-9829-5aa74ffdbf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>431d826b-b982-47a2-b85f-1dbe59082caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ion-cb-3-lbl</value>
      <webElementGuid>9e72ef9a-74bd-4fd4-9105-5a2006a4682e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0d7f0403-96fa-4c3b-8714-67b32ed2b058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dalam Negeri</value>
      <webElementGuid>c9804e4c-60e4-4f10-86d0-93f40de26e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-249dbe50d495f518d14be3a4dd37f321</value>
      <webElementGuid>ae96858a-eacd-48cd-8047-d5910dffc6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'ion-cb-3-lbl']</value>
      <webElementGuid>52582be6-214e-411c-9531-0b29b330ca82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'ion-cb-3-lbl']</value>
      <webElementGuid>30a6e1a0-d6f7-46e4-9de5-7ec2fd365f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-checkbox[(text() = 'Dalam Negeri' or . = 'Dalam Negeri')]</value>
      <webElementGuid>a0eab151-2836-4974-9944-0441b680f434</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
