<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-popover_ion-overlay-21-donesia-829</name>
   <tag></tag>
   <elementGuidId>ce42bcec-2a2c-415e-a99a-40689273aaf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-app > [cssclass=&quot;normal-dropdown&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-app/*[@cssclass = 'normal-dropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-popover</value>
      <webElementGuid>d2ab017f-64c1-43ab-898d-c46bacd451c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>side</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>7cdca914-24d1-486a-afb9-2c89cdaffbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>ios</value>
      <webElementGuid>824e8d32-ac4c-4c98-a4a4-5de518cddd70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>cover</value>
      <webElementGuid>a7d3048c-af60-455f-a793-eedf0f362533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cssclass</name>
      <type>Main</type>
      <value>normal-dropdown</value>
      <webElementGuid>ff09079a-0912-42a3-ad0b-75e4df9b8588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ion-overlay-21</value>
      <webElementGuid>06a23d96-4ad7-4157-9862-f99416e5c0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0274ac30-d378-4ae3-9d86-8ed2c5e4d0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>66330e92-3d52-464b-be98-2655b9f9febd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>normal-dropdown ios popover-desktop popover-side-bottom hydrated</value>
      <webElementGuid>01e2f5c1-ae22-4474-b956-5799a9c3e71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kapten LautReporterIlmuwanAwak PenerbanganHubungan MasyarakatArsitek Kapal LautPenggajian dan FasilitasPerpustakaan dan KuratorFisikawanGeofisikawan Simpan </value>
      <webElementGuid>8677ed16-b6b3-4342-a07d-d40915b9c9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8521f2a1eed302a0b8bf4738269f945c</value>
      <webElementGuid>acb19a75-8d6f-4301-a3ed-a5720f5a6a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ion-app/*[@cssclass = 'normal-dropdown']</value>
      <webElementGuid>431f19cc-a2e0-4e02-8ea2-b4ea5ba9c8b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ion-app/*[@cssclass = 'normal-dropdown']</value>
      <webElementGuid>f6b916b9-8a3f-4a64-aa25-93ad09195e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-popover[@id = 'ion-overlay-21' and (text() = 'Kapten LautReporterIlmuwanAwak PenerbanganHubungan MasyarakatArsitek Kapal LautPenggajian dan FasilitasPerpustakaan dan KuratorFisikawanGeofisikawan Simpan ' or . = 'Kapten LautReporterIlmuwanAwak PenerbanganHubungan MasyarakatArsitek Kapal LautPenggajian dan FasilitasPerpustakaan dan KuratorFisikawanGeofisikawan Simpan ')]</value>
      <webElementGuid>1a819797-aca9-43eb-a348-28c82a6aa501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
